### ISSUE TITLE
Add support for swizzling rgba & stpq

### ISSUE THREAD

**Issue by mfiano** [cbaggers/varjo#165]
If I do this in a frag shader, it complains

```lisp
(if (= (.a color) 0)
      (discard)
      color)
```

However if I change `.a` to `.w`, everything works.

**Comment by cbaggers** [comment]
what are `.a` & `.w` I've never heard of those

**Comment by djeis97** [comment]
Gamebox math defines a bunch of varjo macros for swizzling, like `.x` etc. However when I implemented it I forgot to document that varjo's swizzle special form doesn't support the swizzle groups for `rgba` or `stpq`, so a bunch of unusable macros get generated. In short, real issue here is that you can't `(vari:swizzle color :a)`.

**Comment by cbaggers** [comment]
Ok, so I guess I need to add that then. In the mean time I guess you can tweak you macro generator so `.a` uses `w`, `.g` uses `.y` etc.

I didn't add `rgba` or `stpq` originally as I dont like them, but as varjo is a lot more decoupled from cepl these days I really should :p

**Comment by cbaggers** [comment]
@mfiano btw you have the coolest avatar!

**Comment by mfiano** [comment]
Yeah, I completely forgot that I defined templates to translate the syntax of gamebox-math over to vari for swizzling, sorry about that! Also thanks!

**Comment by cbaggers** [comment]
Fixed on master
