### ISSUE TITLE
Please export these symbols

### ISSUE THREAD

**Issue by mfiano** [cbaggers/varjo#195]
Can you please export these symbols in the varjo package if they are stable enough? I have found them very useful when writing Shadow:

- varjo.internals::get-external-function-by-name
- varjo.internals::stage-obj-to-name 

Thanks!

**Comment by cbaggers** [comment]
`stage-obj-to-name` was an ugly name so I've exported it as `stage-kind`

**Comment by cbaggers** [comment]
I dont think I'll export `get-external-function-by-name` in the public api as it's worthless without exporting the functions  for inspecting function objects and I dont plan on exporting those either (as then I need to document & lock down that api too). `varjo.internals` was only meant for the compiler anyway and I dont guarentee any stability there so there is no advantage over export it there rather than just using `::` (its just as unsafe)

**Comment by cbaggers** [comment]
`stage-kind` has been pushed to master. Thanks for the issue!
