### ISSUE TITLE
stemcells are mangling struct names

### ISSUE THREAD

**Issue by mfiano** [cbaggers/varjo#204]
I'm using keyword symbols as implicit uniforms in vari, so things like `:foo.bar` should be a bar member of foo access, but stemcells are using `safe-glsl-name-string` too early, resulting in this translated to `"FOO46BAR"` instead of `"FOO.BAR"`.

**Comment by cbaggers** [comment]
That seems to be behaving correctly. `:foo.bar` is a single name, just like `λ·θ` is.

Converting to `FOO.BAR` would be silently changing behavior and so I think its a bad choice here

**Comment by cbaggers** [comment]
@djeis97 I just got an earful on irc from mfiano about how I dont understand this issue and that you all agree this is how it should be :p would you mind explaining the issue as to me it seem to be about how symbols are compiled to glsl

**Comment by djeis97** [comment]
I vuagely remember this actually being an issue I was going to report, but I didn’t have the time to make a minimal example then I have even less now. More annoyingly, the example mfiano showed me that convinced me it was a problem has disappeared off his gists (do gists have expiry dates?) so I don’t have enough details to put back together exactly what the problem was. I think it’s had something to do with varjo using safe-glsl-name-string inconsistently when a dotted name is used as a stemcell uniform, but that could easily be me filling in details that aren’t there. Sorry 😕

**Comment by cbaggers** [comment]
@djeis97 no worries at all. I'll leave this closed for now but your description sounds much more like a plausible bug so if it pops up again feel free to reopen this or file a new issue.
