### ISSUE TITLE
Add when and unless

### ISSUE THREAD

**Issue by stacksmith** [cbaggers/varjo#44]
I use these a lot...  It should be pretty easy, no?

**Comment by cbaggers** [comment]
This is a lot like the `if` issue https://github.com/cbaggers/varjo/issues/42 in that `when` & `unless` return values in lisp. Either the tail expression in the body or `nil`.

This is fine in a dynamic language, but statically the type would be `(or tail-expr-type null)`. We can't support runtime type checking in GLSL so we would have to resolve this all statically which is hard.

The alternate approach (which we are also going to use in #42) is to allow these inconsistently typed results `progn` as long as they are in the tail position.

This issue is thus dependent on #42 and will be trivial to fix when it is done

**Comment by stacksmith** [comment]
Understood.  Let's keep it open as a reminder?

**Comment by cbaggers** [comment]
definitely

**Comment by cbaggers** [comment]
These will have a type of `(or <type-of-tail-form> :void)` In not tail positions this won't matter and for tail positions the exists type & function return logic will take care of things.

**Comment by cbaggers** [comment]
With this being done https://github.com/cbaggers/varjo/issues/42 on a branch defining `when` & `unless` was trivial. `unless` is currently not working however this is due to a bug in `not` (I believe it is actually in the function scoring algorithm)

That will be fixed in a seperate ticket. This is effectively done (pending merge)

**Comment by cbaggers** [comment]
unless will be fixed by https://github.com/cbaggers/varjo/issues/72

**Comment by cbaggers** [comment]
#72 is fixed. Much better
